# Generated by Django 5.0.4 on 2024-05-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pg_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=200)),
                ('image1', models.CharField(max_length=200)),
                ('image2', models.CharField(max_length=200)),
                ('image3', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
    ]
