# Generated by Django 5.0.4 on 2024-05-06 10:02

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_data',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.filepath),
        ),
        migrations.AlterField(
            model_name='pg_data',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.filepath),
        ),
        migrations.AlterField(
            model_name='pg_data',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.filepath),
        ),
    ]
