# Generated by Django 5.0.4 on 2024-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_pg_data_image1_alter_pg_data_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg_data',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
