# Generated by Django 5.0.4 on 2024-05-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pg_data_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg_data',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
