# Generated by Django 5.0.4 on 2024-05-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_userprofile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
