# Generated by Django 5.0.4 on 2024-05-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg_data',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
