# Generated by Django 5.0.4 on 2024-05-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_pg_data_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_data',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pg_data',
            name='price',
            field=models.IntegerField(),
        ),
    ]
