# Generated by Django 5.0.4 on 2024-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_pg_data_distance_alter_pg_data_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg_data',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
