# Generated by Django 5.0.4 on 2024-05-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_pg_data_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg_data',
            name='pgfor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
